Changes for PowerAPI monitoring

diff --git a/.github/workflows/snapshot.yml b/.github/workflows/snapshot.yml
--- a/.github/workflows/snapshot.yml
+++ b/.github/workflows/snapshot.yml
@@ -1,43 +1,50 @@
-name: Snapshot
-
-on:
-  push:
-    branches:
-      - master
-
 jobs:
   checkSnapshot:
-    runs-on: ubuntu-20.04
+    runs-on: self-hosted
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-      - name: Set up JDK
-        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
-        with:
-          java-version: '13' # Modern JVM is needed for Java 10+ specific tests
-          distribution: 'adopt'
-      - name: Run tests and javadoc
-        run: ./gradlew check javadoc
+    - continue-on-error: true
+      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
+    - continue-on-error: true
+      name: Set up JDK
+      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
+      with:
+        distribution: adopt
+        java-version: '13'
+    - continue-on-error: true
+      name: Run tests and javadoc
+      run: ./gradlew check javadoc
   publishSnapshot:
-    runs-on: ubuntu-20.04
-    needs: checkSnapshot
-    environment: snapshot
-    env: #change this after a release
+    env:
       BLOCKHOUND_VERSION: 1.0.10.BUILD-SNAPSHOT
+    environment: snapshot
+    needs: checkSnapshot
+    runs-on: self-hosted
     steps:
-      - name: check version
-        if: ${{ !endsWith(env.BLOCKHOUND_VERSION, '.BUILD-SNAPSHOT') }}
-        run: |
-          echo "::error ::$BLOCKHOUND_VERSION is not following the x.y.z.BUILD-SNAPSHOT format"
-          exit 1
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-      - name: Set up JDK
-        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
-        with:
-          java-version: '8'
-          distribution: 'temurin'
-      - name: Publish Snapshot
-        run: ./gradlew --no-daemon -Pversion=$BLOCKHOUND_VERSION publish
-        env:
-          GRADLE_PUBLISH_REPO_URL: https://repo.spring.io/libs-snapshot-local/
-          GRADLE_PUBLISH_MAVEN_USER: ${{secrets.ARTIFACTORY_USERNAME}}
-          GRADLE_PUBLISH_MAVEN_PASSWORD: ${{secrets.ARTIFACTORY_PASSWORD}}
+    - continue-on-error: true
+      if: ${{ !endsWith(env.BLOCKHOUND_VERSION, '.BUILD-SNAPSHOT') }}
+      name: check version
+      run: 'echo "::error ::$BLOCKHOUND_VERSION is not following the x.y.z.BUILD-SNAPSHOT
+        format"
+
+        exit 1
+
+        '
+    - continue-on-error: true
+      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
+    - continue-on-error: true
+      name: Set up JDK
+      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
+      with:
+        distribution: temurin
+        java-version: '8'
+    - continue-on-error: true
+      env:
+        GRADLE_PUBLISH_MAVEN_PASSWORD: ${{secrets.ARTIFACTORY_PASSWORD}}
+        GRADLE_PUBLISH_MAVEN_USER: ${{secrets.ARTIFACTORY_USERNAME}}
+        GRADLE_PUBLISH_REPO_URL: https://repo.spring.io/libs-snapshot-local/
+      name: Publish Snapshot
+      run: ./gradlew --no-daemon -Pversion=$BLOCKHOUND_VERSION publish
+name: Snapshot
+on:
+  repository_dispatch:
+    types: trigger-ga___snapshot.yml
